use_default_settings: true

server:
  port: 10000
  bind_address: "0.0.0.0"
  secret_key: "IWme1Ph8C7EwxhRDOb4DuPcwCQulF6" 

search:
  safe_search: 0
  request_timeout: 5.0
  formats:
    - html
    - json 

plugins:
  - name: Botdetection plugin
    enabled: false 

engines:
  - name: google
    engine: google
    shortcut: go
    timeout: 4.0
  - name: bing
    engine: bing
    shortcut: bi
    timeout: 4.0